import { INodeProperties } from "n8n-workflow";

export const networkProperties: INodeProperties[] = [
  // NETWORK - Paramètres
  {
    displayName: "Send Connection Parameters",
    name: "sendConnectionParams",
    type: "collection",
    placeholder: "Add connection parameter",
    default: {},
    displayOptions: {
      show: {
        resource: ["network"],
        operation: ["sendConnectionRequest"],
      },
    },
    options: [
      {
        displayName: "Profile URL *",
        name: "profileUrl",
        type: "string",
        required: true,
        default: "",
        placeholder: "https://www.linkedin.com/in/username",
        description: "LinkedIn profile URL to connect with",
      },
      {
        displayName: "Connection Message",
        name: "connectionMessage",
        type: "string",
        default: "",
        placeholder: "Hi, I'd like to connect with you!",
        description: "Custom message for connection request",
      },
      {
        displayName: "Country",
        name: "country",
        type: "string",
        default: "FR",
        placeholder: "FR, US, UK, DE, ES, IT, CA, AU, etc.",
        description: "Country code for proxy selection",
      },
    ],
  },
  {
    displayName: "Accept Invitation Parameters",
    name: "acceptInvitationParams",
    type: "collection",
    placeholder: "Add invitation parameter",
    default: {},
    displayOptions: {
      show: {
        resource: ["network"],
        operation: ["acceptConnectionInvitation"],
      },
    },
    options: [
      {
        displayName: "Invitation ID *",
        name: "invitationId",
        type: "string",
        required: true,
        default: "",
        placeholder: "invitation_id_here",
        description: "LinkedIn invitation ID to accept",
      },
      {
        displayName: "Country",
        name: "country",
        type: "string",
        default: "FR",
        placeholder: "FR, US, UK, DE, ES, IT, CA, AU, etc.",
        description: "Country code for proxy selection",
      },
    ],
  },
  {
    displayName: "Withdraw Invitation Parameters",
    name: "withdrawInvitationParams",
    type: "collection",
    placeholder: "Add withdrawal parameter",
    default: {},
    displayOptions: {
      show: {
        resource: ["network"],
        operation: ["withdrawInvitation"],
      },
    },
    options: [
      {
        displayName: "Invitation ID *",
        name: "invitationId",
        type: "string",
        required: true,
        default: "",
        placeholder: "invitation_id_here",
        description: "LinkedIn invitation ID to withdraw",
      },
      {
        displayName: "Country",
        name: "country",
        type: "string",
        default: "FR",
        placeholder: "FR, US, UK, DE, ES, IT, CA, AU, etc.",
        description: "Country code for proxy selection",
      },
    ],
  },
  {
    displayName: "Get Invitation Status Parameters",
    name: "getInvitationStatusParams",
    type: "collection",
    placeholder: "Add status parameter",
    default: {},
    displayOptions: {
      show: {
        resource: ["network"],
        operation: ["getInvitationStatus"],
      },
    },
    options: [
      {
        displayName: "Profile URL *",
        name: "profileUrl",
        type: "string",
        required: true,
        default: "",
        placeholder: "https://www.linkedin.com/in/username",
        description: "LinkedIn profile URL to check invitation status",
      },
      {
        displayName: "Country",
        name: "country",
        type: "string",
        default: "FR",
        placeholder: "FR, US, UK, DE, ES, IT, CA, AU, etc.",
        description: "Country code for proxy selection",
      },
    ],
  },
  {
    displayName: "Get Connections Parameters",
    name: "getConnectionsParams",
    type: "collection",
    placeholder: "Add connection parameter",
    default: {},
    displayOptions: {
      show: {
        resource: ["network"],
        operation: ["getConnections"],
      },
    },
    options: [
      {
        displayName: "Country",
        name: "country",
        type: "string",
        default: "FR",
        placeholder: "FR, US, UK, DE, ES, IT, CA, AU, etc.",
        description: "Country code for proxy selection",
      },
      {
        displayName: "Total Results",
        name: "total_results",
        type: "number",
        default: 10,
        description: "Number of results to return",
      },
      {
        displayName: "Start Page",
        name: "start_page",
        type: "number",
        default: 1,
        description: "Starting page number",
      },
      {
        displayName: "End Page",
        name: "end_page",
        type: "number",
        default: 1,
        description: "Ending page number",
      },
    ],
  },
  {
    displayName: "Get Invitations Parameters",
    name: "getInvitationsParams",
    type: "collection",
    placeholder: "Add invitation parameter",
    default: {},
    displayOptions: {
      show: {
        resource: ["network"],
        operation: ["getReceivedInvitations", "getSentInvitations"],
      },
    },
    options: [
      {
        displayName: "Country",
        name: "country",
        type: "string",
        default: "FR",
        placeholder: "FR, US, UK, DE, ES, IT, CA, AU, etc.",
        description: "Country code for proxy selection",
      },
      {
        displayName: "Invitation Type",
        name: "invitation_type",
        type: "string",
        default: "",
        placeholder: "received or sent",
        description: "Type of invitations to fetch (received or sent)",
      },
      {
        displayName: "Total Results",
        name: "total_results",
        type: "number",
        default: 10,
        description: "Number of results to return",
      },
      {
        displayName: "Start Page",
        name: "start_page",
        type: "number",
        default: 1,
        description: "Starting page number",
      },
      {
        displayName: "End Page",
        name: "end_page",
        type: "number",
        default: 1,
        description: "Ending page number",
      },
    ],
  },
  {
    displayName: "Get Network Recommendations Parameters",
    name: "getNetworkRecommendationsParams",
    type: "collection",
    placeholder: "Add recommendation parameter",
    default: {},
    displayOptions: {
      show: {
        resource: ["network"],
        operation: ["getNetworkRecommendations"],
      },
    },
    options: [
      {
        displayName: "Country",
        name: "country",
        type: "string",
        default: "FR",
        placeholder: "FR, US, UK, DE, ES, IT, CA, AU, etc.",
        description: "Country code for proxy selection",
      },
      {
        displayName: "Total Results",
        name: "total_results",
        type: "number",
        default: 10,
        description: "Number of results to return",
      },
      {
        displayName: "Start Page",
        name: "start_page",
        type: "number",
        default: 1,
        description: "Starting page number",
      },
      {
        displayName: "End Page",
        name: "end_page",
        type: "number",
        default: 1,
        description: "Ending page number",
      },
    ],
  },
];