import { INodeProperties } from "n8n-workflow";

export const profileProperties: INodeProperties[] = [
  // PROFILE - Parameters Linkup
  {
    displayName: "Extract Profile Parameters",
    name: "extractProfileParams",
    type: "collection",
    placeholder: "Add profile parameter",
    default: {},
    displayOptions: {
      show: {
        resource: ["profile"],
        operation: ["extractProfileInfo"],
      },
    },
    options: [
      {
        displayName: "LinkedIn Profile URL *",
        name: "profileUrl",
        type: "string",
        default: "",
        placeholder: "https://www.linkedin.com/in/username",
        description: "LinkedIn profile URL",
      },
      {
        displayName: "Country Code",
        name: "country",
        type: "string",
        default: "FR",
        placeholder: "FR, US, UK, DE, ES, IT, CA, AU, etc.",
        description:
          "Country code for proxy selection (e.g., FR for France, US for United States)",
      },
    ],
  },
  {
    displayName: "Search Profile Parameters",
    name: "searchProfileParams",
    type: "collection",
    placeholder: "Add search parameter",
    default: {},
    displayOptions: {
      show: {
        resource: ["profile"],
        operation: ["searchProfile"],
      },
    },
    options: [
      {
        displayName: "Company URL",
        name: "company_url",
        type: "string",
        default: "",
        placeholder: "https://www.linkedin.com/company/company-name",
        description: "Company LinkedIn URL to filter by",
      },
      {
        displayName: "Location",
        name: "location",
        type: "string",
        default: "",
        placeholder: "San Francisco",
        description: "Location to search in",
      },
      {
        displayName: "School URL",
        name: "school_url",
        type: "string",
        default: "",
        placeholder: "https://www.linkedin.com/school/school-name",
        description: "School LinkedIn URL to filter by",
      },
      {
        displayName: "Network",
        name: "network",
        type: "string",
        default: "",
        placeholder: "1st, 2nd, 3rd",
        description: "Network connection degree",
      },
      {
        displayName: "Keyword",
        name: "keyword",
        type: "string",
        default: "",
        placeholder: "software engineer",
        description: "Search keyword",
      },
      {
        displayName: "Total Results",
        name: "total_results",
        type: "number",
        default: 10,
        description: "Number of results to return",
      },
      {
        displayName: "Start Page",
        name: "start_page",
        type: "number",
        default: 1,
        description: "Starting page number",
      },
      {
        displayName: "End Page",
        name: "end_page",
        type: "number",
        default: 1,
        description: "Ending page number",
      },
      {
        displayName: "Country",
        name: "country",
        type: "string",
        default: "FR",
        placeholder: "FR, US, UK, DE, ES, IT, CA, AU, etc.",
        description: "Country code for proxy selection",
      },
      {
        displayName: "First Name",
        name: "first_name",
        type: "string",
        default: "",
        placeholder: "John",
        description: "First name to filter by",
      },
      {
        displayName: "Last Name",
        name: "last_name",
        type: "string",
        default: "",
        placeholder: "Doe",
        description: "Last name to filter by",
      },
      {
        displayName: "Title",
        name: "title",
        type: "string",
        default: "",
        placeholder: "Software Engineer",
        description: "Job title to filter by",
      },
      {
        displayName: "Login Token",
        name: "login_token",
        type: "string",
        default: "",
        placeholder: "LinkedIn login token",
        description: "LinkedIn authentication token",
      },
      {
        displayName: "Fetch Invitation State",
        name: "fetch_invitation_state",
        type: "boolean",
        default: false,
        description: "Fetch invitation state for results",
      },
    ],
  },
]; 