import { INodeProperties } from "n8n-workflow";

export const recruiterProperties: INodeProperties[] = [
  // RECRUITER - Parameters
  {
    displayName: "Job Parameters",
    name: "jobParams",
    type: "collection",
    placeholder: "Add job parameter",
    default: {},
    displayOptions: {
      show: {
        resource: ["recruiter"],
        operation: ["getCandidates", "publishJob", "closeJob"],
      },
    },
    options: [
      {
        displayName: "Job ID *",
        name: "job_id",
        type: "string",
        default: "",
        placeholder: "job_id_here",
        description: "LinkedIn Recruiter job ID",
      },
      {
        displayName: "Total Results",
        name: "total_results",
        type: "number",
        default: 10,
        description: "Number of results to return",
      },
      {
        displayName: "Start Page",
        name: "start_page",
        type: "number",
        default: 1,
        description: "Starting page number",
      },
      {
        displayName: "End Page",
        name: "end_page",
        type: "number",
        default: 1,
        description: "Ending page number",
      },
      {
        displayName: "Start",
        name: "start",
        type: "string",
        default: "",
        placeholder: "Start date or cursor",
        description: "Start parameter for pagination",
      },
      {
        displayName: "Sort Type",
        name: "sortType",
        type: "string",
        default: "",
        placeholder: "relevance, date, experience",
        description: "Type of sorting to apply",
      },
      {
        displayName: "Sort Order",
        name: "sortOrder",
        type: "string",
        default: "",
        placeholder: "asc, desc",
        description: "Sort order (ascending or descending)",
      },
      {
        displayName: "Ratings",
        name: "ratings",
        type: "string",
        default: "",
        placeholder: "4,5",
        description: "Filter by candidate ratings",
      },
      {
        displayName: "Location",
        name: "location",
        type: "string",
        default: "",
        placeholder: "San Francisco, CA",
        description: "Filter by location",
      },
      {
        displayName: "Years of Experience",
        name: "yearsOfExperience",
        type: "string",
        default: "",
        placeholder: "2-5",
        description: "Filter by years of experience",
      },
      {
        displayName: "Country",
        name: "country",
        type: "string",
        default: "FR",
        placeholder: "FR, US, UK, DE, ES, IT, CA, AU, etc.",
        description: "Country code for proxy selection",
      },
      {
        displayName: "Login Token",
        name: "login_token",
        type: "string",
        default: "",
        placeholder: "LinkedIn login token",
        description: "LinkedIn authentication token",
      },
    ],
  },
  {
    displayName: "Application Parameters",
    name: "applicationParams",
    type: "collection",
    placeholder: "Add application parameter",
    default: {},
    displayOptions: {
      show: {
        resource: ["recruiter"],
        operation: ["getCandidateCV"],
      },
    },
    options: [
      {
        displayName: "Application ID *",
        name: "application_id",
        type: "string",
        default: "",
        placeholder: "application_id_here",
        description: "LinkedIn Recruiter application ID",
      },
      {
        displayName: "Login Token",
        name: "login_token",
        type: "string",
        default: "",
        placeholder: "LinkedIn login token",
        description: "LinkedIn authentication token",
      },
      {
        displayName: "Country",
        name: "country",
        type: "string",
        default: "FR",
        placeholder: "FR, US, UK, DE, ES, IT, CA, AU, etc.",
        description: "Country code for proxy selection",
      },
      {
        displayName: "Login Token",
        name: "login_token",
        type: "string",
        default: "",
        placeholder: "LinkedIn login token",
        description: "LinkedIn authentication token",
      },
    ],
  },
  {
    displayName: "Create Job Parameters",
    name: "createJobParams",
    type: "collection",
    placeholder: "Add job parameter",
    default: {},
    displayOptions: {
      show: {
        resource: ["recruiter"],
        operation: ["createJob"],
      },
    },
    options: [
      {
        displayName: "Login Token",
        name: "login_token",
        type: "string",
        default: "",
        placeholder: "LinkedIn login token",
        description: "LinkedIn authentication token",
      },
      {
        displayName: "Company URL",
        name: "company_url",
        type: "string",
        default: "",
        placeholder: "https://www.linkedin.com/company/company-name",
        description: "Company LinkedIn URL",
      },
      {
        displayName: "Title *",
        name: "title",
        type: "string",
        default: "",
        placeholder: "Software Engineer",
        description: "Title of the job posting",
      },
      {
        displayName: "Place *",
        name: "place",
        type: "string",
        default: "",
        placeholder: "San Francisco, CA",
        description: "Job location",
      },
      {
        displayName: "HTML Description *",
        name: "html_description",
        type: "string",
        default: "",
        placeholder: "We are looking for a talented software engineer...",
        description: "Detailed job description in HTML format",
      },
      {
        displayName: "Employment Status",
        name: "employment_status",
        type: "string",
        default: "",
        placeholder: "full-time, part-time, contract",
        description: "Employment status",
      },
      {
        displayName: "Workplace",
        name: "workplace",
        type: "string",
        default: "",
        placeholder: "remote, on-site, hybrid",
        description: "Workplace type",
      },
      {
        displayName: "Skills",
        name: "skills",
        type: "string",
        default: "",
        placeholder: '["JavaScript", "React", "Node.js"]',
        description: "Required skills as JSON array",
      },
      {
        displayName: "Screening Questions",
        name: "screening_questions",
        type: "string",
        default: "",
        placeholder: '[{"question": "What is your experience with React?"}]',
        description: "Screening questions as JSON array",
      },
      {
        displayName: "Auto Rejection Template",
        name: "auto_rejection_template",
        type: "string",
        default: "",
        placeholder: "Thank you for your application...",
        description: "Auto rejection email template",
      },
      {
        displayName: "Contact Email",
        name: "contact_email",
        type: "string",
        default: "",
        placeholder: "hr@company.com",
        description: "Contact email for applications",
      },
      {
        displayName: "Country",
        name: "country",
        type: "string",
        default: "FR",
        placeholder: "FR, US, UK, DE, ES, IT, CA, AU, etc.",
        description: "Country code for proxy selection",
      },
    ],
  },
  {
    displayName: "Get Job Posts Parameters",
    name: "getJobPostsParams",
    type: "collection",
    placeholder: "Add job parameter",
    default: {},
    displayOptions: {
      show: {
        resource: ["recruiter"],
        operation: ["getJobPosts"],
      },
    },
    options: [
      {
        displayName: "Login Token",
        name: "login_token",
        type: "string",
        default: "",
        placeholder: "LinkedIn login token",
        description: "LinkedIn authentication token",
      },
      {
        displayName: "Job ID",
        name: "job_id",
        type: "string",
        default: "",
        placeholder: "job_id_here",
        description: "LinkedIn Recruiter job ID",
      },
      {
        displayName: "Fetch Details",
        name: "fetch_details",
        type: "boolean",
        default: true,
        description: "Fetch detailed information",
      },
      {
        displayName: "Total Results",
        name: "total_results",
        type: "number",
        default: 10,
        description: "Number of results to return",
      },
      {
        displayName: "Start Page",
        name: "start_page",
        type: "number",
        default: 1,
        description: "Starting page number",
      },
      {
        displayName: "End Page",
        name: "end_page",
        type: "number",
        default: 1,
        description: "Ending page number",
      },
      {
        displayName: "Country",
        name: "country",
        type: "string",
        default: "FR",
        placeholder: "FR, US, UK, DE, ES, IT, CA, AU, etc.",
        description: "Country code for proxy selection",
      },
    ],
  },
]; 