import { INodeProperties } from "n8n-workflow";

export const recruiterProperties: INodeProperties[] = [
  // RECRUITER - Parameters for getCandidates
  {
    displayName: "Get Candidates Parameters",
    name: "getCandidatesParams",
    type: "collection",
    placeholder: "Add candidate parameter",
    default: {},
    displayOptions: {
      show: {
        resource: ["recruiter"],
        operation: ["get candidates"],
      },
    },
    options: [
      {
        displayName: "Job ID *",
        name: "job_id",
        type: "string",
        default: "",
        placeholder: "e.g. jobId123",
        description: "LinkedIn Recruiter job ID",
      },
      {
        displayName: "Total Results",
        name: "total_results",
        type: "number",
        default: 10,
        description: "Number of results to return",
      },
      {
        displayName: "Start Page",
        name: "start_page",
        type: "number",
        default: 1,
        description: "Starting page number",
      },
      {
        displayName: "End Page",
        name: "end_page",
        type: "number",
        default: 1,
        description: "Ending page number",
      },
      {
        displayName: "Start",
        name: "start",
        type: "string",
        default: "",
        placeholder: "e.g. startCursor",
        description: "Start parameter for pagination",
      },
      {
        displayName: "Sort Type",
        name: "sortType",
        type: "string",
        default: "",
        placeholder: "e.g. relevance",
        description: "Type of sorting to apply",
      },
      {
        displayName: "Sort Order",
        name: "sortOrder",
        type: "string",
        default: "",
        placeholder: "e.g. asc",
        description: "Sort order (ascending or descending)",
      },
      {
        displayName: "Ratings",
        name: "ratings",
        type: "string",
        default: "",
        placeholder: "e.g. 4,5",
        description: "Filter by candidate ratings",
      },
      {
        displayName: "Location",
        name: "location",
        type: "string",
        default: "",
        placeholder: "e.g. sanFrancisco",
        description: "Filter by location",
      },
      {
        displayName: "Years of Experience",
        name: "yearsOfExperience",
        type: "string",
        default: "",
        placeholder: "e.g. 2-5",
        description: "Filter by years of experience",
      },
    ],
  },
  // RECRUITER - Parameters for publishJob and closeJob
  {
    displayName: "Publish/Close Job Parameters",
    name: "publishCloseJobParams",
    type: "collection",
    placeholder: "Add job parameter",
    default: {},
    displayOptions: {
      show: {
        resource: ["recruiter"],
        operation: ["publish job", "close job"],
      },
    },
    options: [
      {
        displayName: "Job ID *",
        name: "job_id",
        type: "string",
        default: "",
        placeholder: "e.g. jobId123",
        description: "LinkedIn Recruiter job ID",
      },
    ],
  },
  {
    displayName: "Application Parameters",
    name: "applicationParams",
    type: "collection",
    placeholder: "Add application parameter",
    default: {},
    displayOptions: {
      show: {
        resource: ["recruiter"],
        operation: ["get candidate cv"],
      },
    },
    options: [
      {
        displayName: "Application ID *",
        name: "application_id",
        type: "string",
        default: "",
        placeholder: "e.g. applicationId123",
        description: "LinkedIn Recruiter application ID",
      },
    ],
  },
  {
    displayName: "Create Job Parameters",
    name: "createJobParams",
    type: "collection",
    placeholder: "Add job parameter",
    default: {},
    displayOptions: {
      show: {
        resource: ["recruiter"],
        operation: ["create job"],
      },
    },
    options: [
      {
        displayName: "Company URL *",
        name: "company_url",
        type: "string",
        default: "",
        placeholder: "e.g. https://www.linkedin.com/company/microsoftCorp",
        description: "Company LinkedIn URL",
      },
      {
        displayName: "Title *",
        name: "title",
        type: "string",
        default: "",
        placeholder: "e.g. softwareEngineer",
        description: "Title of the job posting",
      },
      {
        displayName: "Place *",
        name: "place",
        type: "string",
        default: "",
        placeholder: "e.g. sanFrancisco",
        description: "Job location",
      },
      {
        displayName: "HTML Description *",
        name: "html_description",
        type: "string",
        default: "",
        placeholder: "e.g. We are looking for a talented software engineer...",
        description: "Detailed job description in HTML format",
      },
      {
        displayName: "Employment Status",
        name: "employment_status",
        type: "string",
        default: "",
        placeholder: "e.g. fullTime",
        description: "Employment status",
      },
      {
        displayName: "Workplace",
        name: "workplace",
        type: "string",
        default: "",
        placeholder: "e.g. remote",
        description: "Workplace type",
      },
      {
        displayName: "Skills",
        name: "skills",
        type: "string",
        default: "",
        placeholder: 'e.g. ["JavaScript", "React", "Node.js"]',
        description: "Required skills as JSON array",
      },
      {
        displayName: "Screening Questions",
        name: "screening_questions",
        type: "string",
        default: "",
        placeholder:
          'e.g. [{"question": "What is your experience with React?"}]',
        description: "Screening questions as JSON array",
      },
      {
        displayName: "Auto Rejection Template",
        name: "auto_rejection_template",
        type: "string",
        default: "",
        placeholder: "e.g. Thank you for your application...",
        description: "Auto rejection email template",
      },
      {
        displayName: "Contact Email",
        name: "contact_email",
        type: "string",
        default: "",
        placeholder: "e.g. nathan@example.com",
        description: "Contact email for applications",
      },
    ],
  },
  {
    displayName: "Get Job Posts Parameters",
    name: "getJobPostsParams",
    type: "collection",
    placeholder: "Add job parameter",
    default: {},
    displayOptions: {
      show: {
        resource: ["recruiter"],
        operation: ["get job posts"],
      },
    },
    options: [
      {
        displayName: "Job ID",
        name: "job_id",
        type: "string",
        default: "",
        placeholder: "job_id_here",
        description: "LinkedIn Recruiter job ID",
      },
      {
        displayName: "Fetch Details",
        name: "fetch_details",
        type: "boolean",
        default: true,
        description: "Fetch detailed information",
      },
      {
        displayName: "Total Results",
        name: "total_results",
        type: "number",
        default: 10,
        description: "Number of results to return",
      },
      {
        displayName: "Start Page",
        name: "start_page",
        type: "number",
        default: 1,
        description: "Starting page number",
      },
      {
        displayName: "End Page",
        name: "end_page",
        type: "number",
        default: 1,
        description: "Ending page number",
      },
    ],
  },
];
