import { INodeProperties } from "n8n-workflow";

export const recruiterProperties: INodeProperties[] = [
  // RECRUITER - Paramètres
  {
    displayName: "Get Candidates Parameters",
    name: "getCandidatesParams",
    type: "collection",
    placeholder: "Add candidate search parameter",
    default: {},
    displayOptions: {
      show: {
        resource: ["recruiter"],
        operation: ["getCandidates"],
      },
    },
    options: [
      {
        displayName: "Job ID *",
        name: "jobId",
        type: "string",
        required: true,
        default: "",
        placeholder: "job_id_here",
        description: "LinkedIn Recruiter job ID",
      },
      { displayName: "Country", name: "country", type: "string", default: "FR" },
      { displayName: "Location", name: "location", type: "string", default: "" },
      { displayName: "Years Of Experience", name: "yearsOfExperience", type: "number", default: 0 },
      { displayName: "Sort Type", name: "sortType", type: "string", default: "" },
      { displayName: "Sort Order", name: "sortOrder", type: "string", default: "" },
      { displayName: "Ratings", name: "ratings", type: "number", default: 0 },
      { displayName: "Start", name: "start", type: "number", default: 0 },
      { displayName: "Total Results", name: "total_results", type: "number", default: 10 },
      { displayName: "Start Page", name: "start_page", type: "number", default: 1 },
      { displayName: "End Page", name: "end_page", type: "number", default: 1 },
    ],
  },
  {
    displayName: "Job ID *",
    name: "jobId",
    type: "string",
    required: true,
    default: "",
    placeholder: "job_id_here",
    description: "LinkedIn Recruiter job ID",
    displayOptions: {
      show: {
        resource: ["recruiter"],
        operation: ["publishJob", "closeJob"],
      },
    },
  },
  {
    displayName: "Publish/Close Job Parameters",
    name: "publishCloseJobParams",
    type: "collection",
    placeholder: "Add parameter",
    default: {},
    displayOptions: {
      show: {
        resource: ["recruiter"],
        operation: ["publishJob", "closeJob"],
      },
    },
    options: [
      { displayName: "Country", name: "country", type: "string", default: "FR" },
    ],
  },
  {
    displayName: "Application Parameters",
    name: "applicationParams",
    type: "collection",
    placeholder: "Add application parameter",
    default: {},
    displayOptions: {
      show: {
        resource: ["recruiter"],
        operation: ["getCandidateCV"],
      },
    },
    options: [
      {
        displayName: "Application ID *",
        name: "applicationId",
        type: "string",
        required: true,
        default: "",
        placeholder: "application_id_here",
        description: "LinkedIn Recruiter application ID",
      },
    ],
  },
  {
    displayName: "Create Job Parameters",
    name: "createJobParams",
    type: "collection",
    placeholder: "Add job parameter",
    default: {},
    displayOptions: {
      show: {
        resource: ["recruiter"],
        operation: ["createJob"],
      },
    },
    options: [
      {
        displayName: "Job Title *",
        name: "jobTitle",
        type: "string",
        required: true,
        default: "",
        placeholder: "Software Engineer",
        description: "Title of the job posting",
      },
      {
        displayName: "Job Description *",
        name: "jobDescription",
        type: "string",
        required: true,
        default: "",
        placeholder: "We are looking for a talented software engineer...",
        description: "Detailed job description",
      },
      {
        displayName: "Company Name *",
        name: "companyName",
        type: "string",
        required: true,
        default: "",
        placeholder: "Tech Company Inc.",
        description: "Name of the hiring company",
      },
      {
        displayName: "Location *",
        name: "location",
        type: "string",
        required: true,
        default: "",
        placeholder: "San Francisco, CA",
        description: "Job location",
      },
      { displayName: "Country", name: "country", type: "string", default: "FR" },
      { displayName: "Employment Status", name: "employment_status", type: "string", default: "" },
      { displayName: "Workplace", name: "workplace", type: "string", default: "" },
      { displayName: "Skills (JSON or CSV)", name: "skills", type: "string", default: "" },
      { displayName: "Screening Questions (JSON or CSV)", name: "screening_questions", type: "string", default: "" },
      { displayName: "Auto Rejection Template", name: "auto_rejection_template", type: "string", default: "" },
      { displayName: "Contact Email", name: "contact_email", type: "string", default: "" },
    ],
  },
  {
    displayName: "Get Job Posts Parameters",
    name: "getJobPostsParams",
    type: "collection",
    placeholder: "Add job parameter",
    default: {},
    displayOptions: {
      show: {
        resource: ["recruiter"],
        operation: ["getJobPosts"],
      },
    },
    options: [
      { displayName: "Job ID", name: "jobId", type: "string", default: "" },
      { displayName: "Fetch Details", name: "fetchDetails", type: "boolean", default: false },
      {
        displayName: "Country",
        name: "country",
        type: "string",
        default: "FR",
        placeholder: "FR, US, UK, DE, ES, IT, CA, AU, etc.",
        description: "Country code for proxy selection",
      },
      {
        displayName: "Total Results",
        name: "total_results",
        type: "number",
        default: 10,
        description: "Number of results to return",
      },
      {
        displayName: "Start Page",
        name: "start_page",
        type: "number",
        default: 1,
        description: "Starting page number",
      },
      {
        displayName: "End Page",
        name: "end_page",
        type: "number",
        default: 1,
        description: "Ending page number",
      },
    ],
  },
]; 