import { INodeProperties } from "n8n-workflow";

export const signalProperties: INodeProperties[] = [
  // SIGNAL - Parameters
  {
    displayName: "Extract Post Reactions Parameters",
    name: "extractPostReactionsParams",
    type: "collection",
    placeholder: "Add parameter",
    default: {},
    displayOptions: {
      show: {
        resource: ["signal"],
        operation: ["extractPostReactions"],
      },
    },
    options: [
      {
        displayName: "Post URL *",
        name: "post_url",
        type: "string",
        default: "",
        placeholder: "https://www.linkedin.com/posts/activity-123456789",
        description: "LinkedIn post URL to extract data from",
      },
      {
        displayName: "Proxy Country",
        name: "proxy_country",
        type: "string",
        default: "FR",
        placeholder: "FR, US, UK, DE, ES, IT, CA, AU, etc.",
        description: "Country code for proxy selection",
      },
      {
        displayName: "Total Results",
        name: "total_results",
        type: "number",
        default: 10,
        description: "Number of results to return",
      },

      {
        displayName: "Start Page",
        name: "start_page",
        type: "number",
        default: 1,
        description: "Starting page number",
      },
      {
        displayName: "End Page",
        name: "end_page",
        type: "number",
        default: 1,
        description: "Ending page number",
      },
    ],
  },
  {
    displayName: "Extract Post Comments Parameters",
    name: "extractPostCommentsParams",
    type: "collection",
    placeholder: "Add parameter",
    default: {},
    displayOptions: {
      show: {
        resource: ["signal"],
        operation: ["extractPostComments"],
      },
    },
    options: [
      {
        displayName: "Post URL *",
        name: "post_url",
        type: "string",
        default: "",
        placeholder: "https://www.linkedin.com/posts/activity-123456789",
        description: "LinkedIn post URL to extract data from",
      },
      {
        displayName: "Proxy Country",
        name: "proxy_country",
        type: "string",
        default: "FR",
        placeholder: "FR, US, UK, DE, ES, IT, CA, AU, etc.",
        description: "Country code for proxy selection",
      },
      {
        displayName: "Total Results",
        name: "total_results",
        type: "number",
        default: 10,
        description: "Number of results to return",
      },

      {
        displayName: "Start Page",
        name: "start_page",
        type: "number",
        default: 1,
        description: "Starting page number",
      },
      {
        displayName: "End Page",
        name: "end_page",
        type: "number",
        default: 1,
        description: "Ending page number",
      },
    ],
  },
  {
    displayName: "Extract Profile Reactions Parameters",
    name: "extractProfileReactionsParams",
    type: "collection",
    placeholder: "Add parameter",
    default: {},
    displayOptions: {
      show: {
        resource: ["signal"],
        operation: ["extractProfileReactions"],
      },
    },
    options: [
      {
        displayName: "Profile URL *",
        name: "profile_url",
        type: "string",
        default: "",
        placeholder: "https://www.linkedin.com/in/username",
        description: "LinkedIn profile URL to extract data from",
      },
      {
        displayName: "Proxy Country",
        name: "proxy_country",
        type: "string",
        default: "FR",
        placeholder: "FR, US, UK, DE, ES, IT, CA, AU, etc.",
        description: "Country code for proxy selection",
      },
      {
        displayName: "Total Results",
        name: "total_results",
        type: "number",
        default: 10,
        description: "Number of results to return",
      },

      {
        displayName: "Start Page",
        name: "start_page",
        type: "number",
        default: 1,
        description: "Starting page number",
      },
      {
        displayName: "End Page",
        name: "end_page",
        type: "number",
        default: 1,
        description: "Ending page number",
      },
      {
        displayName: "Cursor",
        name: "cursor",
        type: "string",
        default: "",
        placeholder: "Pagination cursor",
        description: "Cursor for pagination",
      },
    ],
  },
  {
    displayName: "Extract Profile Comments Parameters",
    name: "extractProfileCommentsParams",
    type: "collection",
    placeholder: "Add parameter",
    default: {},
    displayOptions: {
      show: {
        resource: ["signal"],
        operation: ["extractProfileComments"],
      },
    },
    options: [
      {
        displayName: "Profile URL *",
        name: "profile_url",
        type: "string",
        default: "",
        placeholder: "https://www.linkedin.com/in/username",
        description: "LinkedIn profile URL to extract data from",
      },
      {
        displayName: "Proxy Country",
        name: "proxy_country",
        type: "string",
        default: "FR",
        placeholder: "FR, US, UK, DE, ES, IT, CA, AU, etc.",
        description: "Country code for proxy selection",
      },
      {
        displayName: "Total Results",
        name: "total_results",
        type: "number",
        default: 10,
        description: "Number of results to return",
      },

      {
        displayName: "Start Page",
        name: "start_page",
        type: "number",
        default: 1,
        description: "Starting page number",
      },
      {
        displayName: "End Page",
        name: "end_page",
        type: "number",
        default: 1,
        description: "Ending page number",
      },
      {
        displayName: "Cursor",
        name: "cursor",
        type: "string",
        default: "",
        placeholder: "Pagination cursor",
        description: "Cursor for pagination",
      },
    ],
  },
  {
    displayName: "Extract Profile Posts Parameters",
    name: "extractProfilePostsParams",
    type: "collection",
    placeholder: "Add parameter",
    default: {},
    displayOptions: {
      show: {
        resource: ["signal"],
        operation: ["extractProfilePosts"],
      },
    },
    options: [
      {
        displayName: "Profile URL *",
        name: "profile_url",
        type: "string",
        default: "",
        placeholder: "https://www.linkedin.com/in/username",
        description: "LinkedIn profile URL to extract data from",
      },
      {
        displayName: "Proxy Country",
        name: "proxy_country",
        type: "string",
        default: "FR",
        placeholder: "FR, US, UK, DE, ES, IT, CA, AU, etc.",
        description: "Country code for proxy selection",
      },
      {
        displayName: "Total Results",
        name: "total_results",
        type: "number",
        default: 10,
        description: "Number of results to return",
      },
      {
        displayName: "Post Type",
        name: "post_type",
        type: "string",
        default: "ALL",
        placeholder: "ALL, ARTICLE, VIDEO, PHOTO, DOCUMENT",
        description: "Type of posts to extract",
      },
      {
        displayName: "Sort By",
        name: "sort_by",
        type: "string",
        default: "DATE_POSTED",
        placeholder: "RELEVANCE, DATE_POSTED",
        description: "Sort order for posts",
      },
      {
        displayName: "Keyword",
        name: "keyword",
        type: "string",
        default: "",
        placeholder: "Filter posts by keyword",
        description: "Keyword to filter posts",
      },
      {
        displayName: "Post Date",
        name: "post_date",
        type: "string",
        default: "",
        placeholder: "PAST_24_HOURS, PAST_WEEK, PAST_MONTH",
        description: "Date filter for posts",
      },

      {
        displayName: "Start Page",
        name: "start_page",
        type: "number",
        default: 1,
        description: "Starting page number",
      },
      {
        displayName: "End Page",
        name: "end_page",
        type: "number",
        default: 1,
        description: "Ending page number",
      },
    ],
  },
  {
    displayName: "Extract Company Posts Parameters",
    name: "extractCompanyPostsParams",
    type: "collection",
    placeholder: "Add parameter",
    default: {},
    displayOptions: {
      show: {
        resource: ["signal"],
        operation: ["extractCompanyPosts"],
      },
    },
    options: [
      {
        displayName: "Company URL *",
        name: "company_url",
        type: "string",
        default: "",
        placeholder: "https://www.linkedin.com/company/microsoft",
        description: "LinkedIn company URL to extract data from",
      },
      {
        displayName: "Proxy Country",
        name: "proxy_country",
        type: "string",
        default: "FR",
        placeholder: "FR, US, UK, DE, ES, IT, CA, AU, etc.",
        description: "Country code for proxy selection",
      },
      {
        displayName: "Total Results",
        name: "total_results",
        type: "number",
        default: 10,
        description: "Number of results to return",
      },
      {
        displayName: "Post Type",
        name: "post_type",
        type: "string",
        default: "ALL",
        placeholder: "ALL, ARTICLE, VIDEO, PHOTO, DOCUMENT",
        description: "Type of posts to extract",
      },
      {
        displayName: "Sort By",
        name: "sort_by",
        type: "string",
        default: "DATE_POSTED",
        placeholder: "RELEVANCE, DATE_POSTED",
        description: "Sort order for posts",
      },
      {
        displayName: "Keyword",
        name: "keyword",
        type: "string",
        default: "",
        placeholder: "Filter posts by keyword",
        description: "Keyword to filter posts",
      },
      {
        displayName: "Post Date",
        name: "post_date",
        type: "string",
        default: "",
        placeholder: "PAST_24_HOURS, PAST_WEEK, PAST_MONTH",
        description: "Date filter for posts",
      },

      {
        displayName: "Start Page",
        name: "start_page",
        type: "number",
        default: 1,
        description: "Starting page number",
      },
      {
        displayName: "End Page",
        name: "end_page",
        type: "number",
        default: 1,
        description: "Ending page number",
      },
    ],
  },
];