import { INodeProperties } from "n8n-workflow";

export const signalProperties: INodeProperties[] = [
  // Signal operations
  {
    displayName: "Operation",
    name: "operation",
    type: "options",
    noDataExpression: true,
    displayOptions: {
      show: {
        resource: ["signal"],
      },
    },
    options: [
      {
        name: "Extract post reactions",
        value: "extractPostReactions",
        description: "Extract reactions from a LinkedIn post",
      },
      {
        name: "Extract post comments",
        value: "extractPostComments",
        description: "Extract comments from a LinkedIn post",
      },
      {
        name: "Extract profile reactions",
        value: "extractProfileReactions",
        description: "Extract reactions from a LinkedIn profile",
      },
      {
        name: "Extract profile comments",
        value: "extractProfileComments",
        description: "Extract comments from a LinkedIn profile",
      },
      {
        name: "Extract profile posts",
        value: "extractProfilePosts",
        description: "Extract posts from a LinkedIn profile",
      },
      {
        name: "Extract company posts",
        value: "extractCompanyPosts",
        description: "Extract posts from a LinkedIn company",
      },
    ],
    default: "extractPostReactions",
  },

  // SIGNAL - Paramètres
  {
    displayName: "Post URL *",
    name: "post_url",
    type: "string",
    default: "",
    required: true,
    placeholder: "https://www.linkedin.com/posts/activity-123456789",
    displayOptions: {
      show: {
        resource: ["signal"],
        operation: ["extractPostReactions", "extractPostComments"],
      },
    },
    description: "LinkedIn post URL to extract data from",
  },
  {
    displayName: "Profile URL *",
    name: "profile_url",
    type: "string",
    default: "",
    required: true,
    placeholder: "https://www.linkedin.com/in/username",
    displayOptions: {
      show: {
        resource: ["signal"],
        operation: ["extractProfileReactions", "extractProfileComments", "extractProfilePosts"],
      },
    },
    description: "LinkedIn profile URL to extract data from",
  },
  {
    displayName: "Company URL *",
    name: "company_url",
    type: "string",
    default: "",
    required: true,
    placeholder: "https://www.linkedin.com/company/microsoft",
    displayOptions: {
      show: {
        resource: ["signal"],
        operation: ["extractCompanyPosts"],
      },
    },
    description: "LinkedIn company URL to extract posts from",
  },
  {
    displayName: "Signal Post Reactions Parameters",
    name: "signalPostReactionsParams",
    type: "collection",
    placeholder: "Add signal parameter",
    default: {},
    displayOptions: {
      show: {
        resource: ["signal"],
        operation: ["extractPostReactions"],
      },
    },
    options: [
      {
        displayName: "Proxy Country",
        name: "proxy_country",
        type: "string",
        default: "FR",
        placeholder: "FR, US, UK, DE, ES, IT, CA, AU, etc.",
        description: "Country code for proxy selection",
      },
      {
        displayName: "Total Results",
        name: "total_results",
        type: "number",
        default: 10,
        description: "Number of results to return",
      },
      {
        displayName: "Use Pagination",
        name: "use_pagination",
        type: "boolean",
        default: false,
        description: "Whether to use pagination",
      },
      {
        displayName: "Start Page",
        name: "start_page",
        type: "number",
        default: 1,
        description: "Starting page number",
      },
      {
        displayName: "End Page",
        name: "end_page",
        type: "number",
        default: 1,
        description: "Ending page number",
      },
    ],
  },
  {
    displayName: "Signal Post Comments Parameters",
    name: "signalPostCommentsParams",
    type: "collection",
    placeholder: "Add signal parameter",
    default: {},
    displayOptions: {
      show: {
        resource: ["signal"],
        operation: ["extractPostComments"],
      },
    },
    options: [
      {
        displayName: "Proxy Country",
        name: "proxy_country",
        type: "string",
        default: "FR",
        placeholder: "FR, US, UK, DE, ES, IT, CA, AU, etc.",
        description: "Country code for proxy selection",
      },
      {
        displayName: "Total Results",
        name: "total_results",
        type: "number",
        default: 10,
        description: "Number of results to return",
      },
      {
        displayName: "Use Pagination",
        name: "use_pagination",
        type: "boolean",
        default: false,
        description: "Whether to use pagination",
      },
      {
        displayName: "Start Page",
        name: "start_page",
        type: "number",
        default: 1,
        description: "Starting page number",
      },
      {
        displayName: "End Page",
        name: "end_page",
        type: "number",
        default: 1,
        description: "Ending page number",
      },
    ],
  },
  {
    displayName: "Signal Profile Reactions Parameters",
    name: "signalProfileReactionsParams",
    type: "collection",
    placeholder: "Add signal parameter",
    default: {},
    displayOptions: {
      show: {
        resource: ["signal"],
        operation: ["extractProfileReactions"],
      },
    },
    options: [
      {
        displayName: "Proxy Country",
        name: "proxy_country",
        type: "string",
        default: "FR",
        placeholder: "FR, US, UK, DE, ES, IT, CA, AU, etc.",
        description: "Country code for proxy selection",
      },
      {
        displayName: "Total Results",
        name: "total_results",
        type: "number",
        default: 10,
        description: "Number of results to return",
      },
      {
        displayName: "Start Page",
        name: "start_page",
        type: "number",
        default: 1,
        description: "Starting page number",
      },
      {
        displayName: "End Page",
        name: "end_page",
        type: "number",
        default: 1,
        description: "Ending page number",
      },
      {
        displayName: "Cursor",
        name: "cursor",
        type: "string",
        default: "",
        placeholder: "cursor_value",
        description: "Cursor for pagination",
      },
    ],
  },
  {
    displayName: "Signal Profile Comments Parameters",
    name: "signalProfileCommentsParams",
    type: "collection",
    placeholder: "Add signal parameter",
    default: {},
    displayOptions: {
      show: {
        resource: ["signal"],
        operation: ["extractProfileComments"],
      },
    },
    options: [
      {
        displayName: "Proxy Country",
        name: "proxy_country",
        type: "string",
        default: "FR",
        placeholder: "FR, US, UK, DE, ES, IT, CA, AU, etc.",
        description: "Country code for proxy selection",
      },
      {
        displayName: "Total Results",
        name: "total_results",
        type: "number",
        default: 10,
        description: "Number of results to return",
      },
      {
        displayName: "Start Page",
        name: "start_page",
        type: "number",
        default: 1,
        description: "Starting page number",
      },
      {
        displayName: "End Page",
        name: "end_page",
        type: "number",
        default: 1,
        description: "Ending page number",
      },
      {
        displayName: "Cursor",
        name: "cursor",
        type: "string",
        default: "",
        placeholder: "cursor_value",
        description: "Cursor for pagination",
      },
    ],
  },
  {
    displayName: "Signal Profile Posts Parameters",
    name: "signalProfilePostsParams",
    type: "collection",
    placeholder: "Add signal parameter",
    default: {},
    displayOptions: {
      show: {
        resource: ["signal"],
        operation: ["extractProfilePosts"],
      },
    },
    options: [
      {
        displayName: "Proxy Country",
        name: "proxy_country",
        type: "string",
        default: "FR",
        placeholder: "FR, US, UK, DE, ES, IT, CA, AU, etc.",
        description: "Country code for proxy selection",
      },
      {
        displayName: "Total Results",
        name: "total_results",
        type: "number",
        default: 10,
        description: "Number of results to return",
      },
      {
        displayName: "Post Type",
        name: "post_type",
        type: "string",
        default: "",
        placeholder: "article, video, image",
        description: "Type of post to filter by",
      },
      {
        displayName: "Sort By",
        name: "sort_by",
        type: "string",
        default: "",
        placeholder: "relevance, date",
        description: "Sort order for results",
      },
      {
        displayName: "Keyword",
        name: "keyword",
        type: "string",
        default: "",
        placeholder: "AI technology",
        description: "Keyword to filter posts by",
      },
      {
        displayName: "Post Date",
        name: "post_date",
        type: "string",
        default: "",
        placeholder: "2024-01-01",
        description: "Date filter for posts",
      },
      {
        displayName: "Use Pagination",
        name: "use_pagination",
        type: "boolean",
        default: false,
        description: "Whether to use pagination",
      },
      {
        displayName: "Start Page",
        name: "start_page",
        type: "number",
        default: 1,
        description: "Starting page number",
      },
      {
        displayName: "End Page",
        name: "end_page",
        type: "number",
        default: 1,
        description: "Ending page number",
      },
    ],
  },
  {
    displayName: "Signal Company Posts Parameters",
    name: "signalCompanyPostsParams",
    type: "collection",
    placeholder: "Add signal parameter",
    default: {},
    displayOptions: {
      show: {
        resource: ["signal"],
        operation: ["extractCompanyPosts"],
      },
    },
    options: [
      {
        displayName: "Proxy Country",
        name: "proxy_country",
        type: "string",
        default: "FR",
        placeholder: "FR, US, UK, DE, ES, IT, CA, AU, etc.",
        description: "Country code for proxy selection",
      },
      {
        displayName: "Total Results",
        name: "total_results",
        type: "number",
        default: 10,
        description: "Number of results to return",
      },
      {
        displayName: "Post Type",
        name: "post_type",
        type: "string",
        default: "",
        placeholder: "article, video, image",
        description: "Type of post to filter by",
      },
      {
        displayName: "Sort By",
        name: "sort_by",
        type: "string",
        default: "",
        placeholder: "relevance, date",
        description: "Sort order for results",
      },
      {
        displayName: "Keyword",
        name: "keyword",
        type: "string",
        default: "",
        placeholder: "AI technology",
        description: "Keyword to filter posts by",
      },
      {
        displayName: "Post Date",
        name: "post_date",
        type: "string",
        default: "",
        placeholder: "2024-01-01",
        description: "Date filter for posts",
      },
      {
        displayName: "Use Pagination",
        name: "use_pagination",
        type: "boolean",
        default: false,
        description: "Whether to use pagination",
      },
      {
        displayName: "Start Page",
        name: "start_page",
        type: "number",
        default: 1,
        description: "Starting page number",
      },
      {
        displayName: "End Page",
        name: "end_page",
        type: "number",
        default: 1,
        description: "Ending page number",
      },
    ],
  },
]; 